name: Flutter CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          cache: true
          flutter-version: 3.24.5
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings # remove flags if you want to treat infos and warnings as errors

      - name: Run tests
        run: flutter test