name: Flutter CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Backend Setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Create Firebase credentials
        run: |
          cd backend
          echo '${{ secrets.FIREBASE_CREDENTIALS_JSON }}' > firebase_credentials.json

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Start backend server
        run: |
          cd backend
          python run.py &
          echo "BACKEND_PID=$!" >> $GITHUB_ENV
        env:
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_CREDENTIALS_PATH: "firebase_credentials.json"

      # Flutter Setup and Validation
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          cache: true
          flutter-version: 3.24.5
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test

      # Cleanup
      - name: Stop backend server
        if: always()
        run: kill ${{ env.BACKEND_PID }}